'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Asistan
    Public Property AsistanID As Integer
    Public Property AsistanAdi As String
    Public Property Mail As String

    Public Overridable Property Liste As ICollection(Of Liste) = New HashSet(Of Liste)

End Class
