'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Derslik
    Public Property DerslikID As Integer
    Public Property DerslikAdi As String
    Public Property Kapasite As Integer

    Public Overridable Property Liste As ICollection(Of Liste) = New HashSet(Of Liste)

End Class
