'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Dersler
    Public Property DersKodu As String
    Public Property DersAdi As String

    Public Overridable Property Sinav As ICollection(Of Sinav) = New HashSet(Of Sinav)

End Class
