'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GorselDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GorselDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Asistan() As DbSet(Of Asistan)
    Public Overridable Property Dersler() As DbSet(Of Dersler)
    Public Overridable Property Derslik() As DbSet(Of Derslik)
    Public Overridable Property Donem() As DbSet(Of Donem)
    Public Overridable Property Liste() As DbSet(Of Liste)
    Public Overridable Property Sinav() As DbSet(Of Sinav)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Tarihler() As DbSet(Of Tarihler)

End Class
