'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sinav
    Public Property SinavID As Integer
    Public Property DersKodu As String
    Public Property DonemID As Integer
    Public Property TarihID As Integer
    Public Property SinavTuru As String

    Public Overridable Property Dersler As Dersler
    Public Overridable Property Donem As Donem
    Public Overridable Property Liste As ICollection(Of Liste) = New HashSet(Of Liste)
    Public Overridable Property Tarihler As Tarihler

End Class
